# Generated by Django 4.2.20 on 2025-04-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_diff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdffile',
            old_name='file',
            new_name='pdf1',
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='pdf2',
            field=models.FileField(default='default.pdf', upload_to='pdfs/'),
        ),
    ]
